POST http://localhost:7000/api/users
Content-Type: application/json

{
    "name":"krak",
    "email":"krakpipe@gmail.com",
    "password":"krak"
    
}

###
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
    "email":"jjnnjnmkom@gmail.com",
    "password":"krakjk"
}

####
GET http://localhost:7000/api/users
Content-Type: application/json

###
GET http://localhost:7000/api/auth/refresh_token
Content-Type: application/json

